kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: alpine
  commands:
  - echo $USERNAME
  - echo $PASSWORD 
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password

---
kind: secret
name: username
get:
  path: docker
  name: username

---
kind: secret
name: password
get:
  path: docker
  name: password
